#!/usr/bin/env bash
# Configures a new Nginx server allow /redirect_me to be redirected to anoteher page.
# Redirected must be a "301 Moved Permanebtly"


sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install nginx -y

# Starting nginx service
sudo service nginx start
#
# Redirection string
new_string="replace_line /redirect_me https://www.youtube.com/watch?v=rv7uzsBm8zw"

# Give the user ownership to website files for easy editing
sudo sed -i "54i $new_string" /etc/nginx/sites-available/default

# Restart nginx service - stop currently running nginx and start a new nginx
sudo service nginx restart

# Reload configuration - Nginx web server without actually stopping and starting the server
sudo service nginx reload
