#!/usr/bin/env bash
# Configures a new Nginx server allow /redirect_me to be redirected to anoteher page.
# Redirected must be a "301 Moved Permanebtly"


sudo apt-get update -y
sudo apt-get install nginx -y

#
# Redirection string
#new_string="location /redirect_me {\n\t\treturn 301  https://www.youtube.com/watch?v=rv7uzsBm8zw\n\t}"

# Give the user ownership to website files for easy editing
sudo sed -i '/server_name _;/a \\t location /redirect_me {\n\t\t return 301  https://www.youtube.com/watch?v=rv7uzsBm8zw;\n\t}' /etc/nginx/sites-available/default

# Reload configuration - Nginx web server without actually stopping and starting the server
sudo service nginx restart
