#!/usr/bin/env bash
# Configures a new Nginx server to allow "Ceci n'est pas ume page" to be displayed on custom 404 page.
# Redirected must be a "301 Moved Permanebtly"


sudo apt-get update -y
sudo apt-get install nginx -y

# create a hello world page
echo "Hello world!" |sudo tee /var/www/html/index.html

# 404 page
# custom_string="location /404 page {\n\t\treturn HTTP 404 error https://www.youtube.com/watch?v=rv7uzsBm8zw\n\t}"

# Redirection page
sudo sed -i '/server_name _;/a \\t location /redirect_me {\n\t\t return 301  https://www.youtube.com/watch?v=rv7uzsBm8zw;\n\t}' /etc/nginx/sites-available/default

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

# Configure Nginx to use the custom 404 page
sudo sed -i '/server_name _;/a \        error_page 404 /custom_404.html;\n        location = /custom_404.html {\n                internal;\n        }' /etc/nginx/sites-available/default

# Reload configuration - Nginx web server without actually stopping and starting the server
sudo service nginx restart
