#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom
# header (on web-01 and web-02).
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of
# the server Nginx is running on.
#
sudo apt-get update -y
sudo apt-get install nginx -y
#
# Starting nginx service
sudo service nginx start
#
# Allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'
#
# Add custom header configuration to Nginx
sudo sed -i '24i\        add_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default
#
# restart the web server after updating the settings
sudo service nginx restart
