#!/usr/bin/env bash
# Installs and setup haproxy

sudo apt-get install -y software-properties-common
sudo apt-get-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get install -y haproxy

echo "ENABLED=1" >> /etc/default/haproxy

# listens to web1 and web2 servers
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 141654-web-01 52.3.242.172:80 check
   server 141654-web-02 52.91.153.85:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start

