#!/usr/bin/env bash
# Displays information about the file 'school'.

iif [ -e "school" ]
then
	echo "school file exists"
	if [ -s "school" ]
	then
		echo "schoo file is not empty"
	else
		echo "school file is empty"
	fi

	if [ -f "school" ]
	then
		echo "echo "school is s regular file"
	fi
else
	echo "school file does not exist"
fi
