#!/usr/bin/env bash                                                            
# Nginx to run as nginx user                                                          
service nginx stop
userdel nginx
useradd -u 101 -g nginx
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
service nginx reload
service nginx restart
